package eu.jasperlorelai.antigone.nms.shared.parameters.mob;

import io.papermc.paper.entity.SchoolableFish;

import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.monster.*;
import net.minecraft.world.entity.raid.Raider;
import net.minecraft.world.entity.PathfinderMob;
import net.minecraft.world.entity.TamableAnimal;
import net.minecraft.world.entity.animal.Animal;
import net.minecraft.world.entity.animal.fox.Fox;
import net.minecraft.world.entity.animal.bee.Bee;
import net.minecraft.world.entity.animal.wolf.Wolf;
import net.minecraft.world.entity.monster.illager.*;
import net.minecraft.world.entity.animal.feline.Cat;
import net.minecraft.world.entity.animal.squid.Squid;
import net.minecraft.world.entity.animal.panda.Panda;
import net.minecraft.world.entity.animal.equine.Llama;
import net.minecraft.world.entity.animal.turtle.Turtle;
import net.minecraft.world.entity.animal.rabbit.Rabbit;
import net.minecraft.world.entity.animal.feline.Ocelot;
import net.minecraft.world.entity.monster.zombie.Zombie;
import net.minecraft.world.entity.monster.spider.Spider;
import net.minecraft.world.entity.animal.fish.Pufferfish;
import net.minecraft.world.entity.boss.wither.WitherBoss;
import net.minecraft.world.entity.monster.zombie.Drowned;
import net.minecraft.world.entity.animal.golem.IronGolem;
import net.minecraft.world.entity.animal.dolphin.Dolphin;
import net.minecraft.world.entity.animal.fish.AbstractFish;
import net.minecraft.world.entity.animal.polarbear.PolarBear;
import net.minecraft.world.entity.animal.equine.SkeletonHorse;
import net.minecraft.world.entity.animal.equine.AbstractHorse;
import net.minecraft.world.entity.animal.happyghast.HappyGhast;
import net.minecraft.world.entity.npc.villager.AbstractVillager;
import net.minecraft.world.entity.animal.fish.AbstractSchoolingFish;
import net.minecraft.world.entity.animal.parrot.ShoulderRidingEntity;
import net.minecraft.world.entity.npc.wanderingtrader.WanderingTrader;

import eu.jasperlorelai.antigone.nms.shared.util.Description;

public class MobParameters {

	public static final MobParameter<Mob> Mob = MobParameter.of(Mob.class, Description.ofEntityInterface(org.bukkit.entity.Mob.class));
	public static final MobParameter<PathfinderMob> PathfinderMob = MobParameter.of(PathfinderMob.class, Description.ofEntityInterface(org.bukkit.entity.Creature.class));
	public static final MobParameter<Animal> Animal = MobParameter.of(Animal.class, Description.ofEntityInterface(org.bukkit.entity.Animals.class));
	public static final MobParameter<Wolf> Wolf = MobParameter.of(Wolf.class, Description.ofClass(org.bukkit.entity.Wolf.class));
	public static final MobParameter<Cat> Cat = MobParameter.of(Cat.class, Description.ofClass(org.bukkit.entity.Cat.class));
	public static final MobParameter<Dolphin> Dolphin = MobParameter.of(Dolphin.class, Description.ofClass(org.bukkit.entity.Dolphin.class));
	public static final MobParameter<TamableAnimal> TamableAnimal = MobParameter.of(TamableAnimal.class, Description.ofEntityInterface(org.bukkit.entity.Tameable.class));
	public static final MobParameter<Llama> Llama = MobParameter.of(Llama.class, Description.ofClass(org.bukkit.entity.Llama.class));
	public static final MobParameter<AbstractVillager> AbstractVillager = MobParameter.of(AbstractVillager.class, Description.ofEntityInterface(org.bukkit.entity.AbstractVillager.class));
	public static final MobParameter<AbstractIllager> AbstractIllager = MobParameter.of(AbstractIllager.class, Description.ofEntityInterface(org.bukkit.entity.Illager.class));
	public static final MobParameter<IronGolem> IronGolem = MobParameter.of(IronGolem.class, Description.ofClass(org.bukkit.entity.IronGolem.class));
	public static final MobParameter<Raider> Raider = MobParameter.of(Raider.class, Description.ofEntityInterface(org.bukkit.entity.Raider.class));
	public static final MobParameter<AbstractHorse> AbstractHorse = MobParameter.of(AbstractHorse.class, Description.ofEntityInterface(org.bukkit.entity.AbstractHorse.class));
	public static final MobParameter<Creeper> Creeper = MobParameter.of(Creeper.class, Description.ofClass(org.bukkit.entity.Creeper.class));
	public static final MobParameter<Zombie> Zombie = MobParameter.of(Zombie.class, Description.ofClass(org.bukkit.entity.Zombie.class));
	public static final MobParameter<SkeletonHorse> SkeletonHorse = MobParameter.of(SkeletonHorse.class, Description.ofClass(org.bukkit.entity.SkeletonHorse.class));
	public static final MobParameter<Vindicator> Vindicator = MobParameter.of(Vindicator.class, Description.ofClass(org.bukkit.entity.Vindicator.class));
	public static final MobParameter<WanderingTrader> WanderingTrader = MobParameter.of(WanderingTrader.class, Description.ofClass(org.bukkit.entity.WanderingTrader.class));
	public static final MobParameter<Turtle> Turtle = MobParameter.of(Turtle.class, Description.ofClass(org.bukkit.entity.Turtle.class));
	public static final MobParameter<Strider> Strider = MobParameter.of(Strider.class, Description.ofClass(org.bukkit.entity.Strider.class));
	public static final MobParameter<Squid> Squid = MobParameter.of(Squid.class, Description.ofClass(org.bukkit.entity.Squid.class));
	public static final MobParameter<Spider> Spider = MobParameter.of(Spider.class, Description.ofClass(org.bukkit.entity.Spider.class));
	public static final MobParameter<Fox> Fox = MobParameter.of(Fox.class, Description.ofClass(org.bukkit.entity.Fox.class));
	public static final MobParameter<Slime> Slime = MobParameter.of(Slime.class, Description.ofClass(org.bukkit.entity.Slime.class));
	public static final MobParameter<Silverfish> Silverfish = MobParameter.of(Silverfish.class, Description.ofClass(org.bukkit.entity.Silverfish.class));
	public static final MobParameter<Shulker> Shulker = MobParameter.of(Shulker.class, Description.ofClass(org.bukkit.entity.Shulker.class));
	public static final MobParameter<Ghast> Ghast = MobParameter.of(Ghast.class, Description.ofClass(org.bukkit.entity.Ghast.class));
	public static final MobParameter<HappyGhast> HappyGhast = MobParameter.of(HappyGhast.class, Description.ofClass(org.bukkit.entity.HappyGhast.class));
	public static final MobParameter<Rabbit> Rabbit = MobParameter.of(Rabbit.class, Description.ofClass(org.bukkit.entity.Rabbit.class));
	public static final MobParameter<Pufferfish> Pufferfish = MobParameter.of(Pufferfish.class, Description.ofClass(org.bukkit.entity.PufferFish.class));
	public static final MobParameter<Panda> Panda = MobParameter.of(Panda.class, Description.ofClass(org.bukkit.entity.Panda.class));
	public static final MobParameter<Ocelot> Ocelot = MobParameter.of(Ocelot.class, Description.ofClass(org.bukkit.entity.Ocelot.class));
	public static final MobParameter<PatrollingMonster> PatrollingMonster = MobParameter.of(PatrollingMonster.class, Description.ofEntityInterface("Patrolling ", org.bukkit.entity.Raider.class));
	public static final MobParameter<Guardian> Guardian = MobParameter.of(Guardian.class, Description.ofClass(org.bukkit.entity.Guardian.class));
	public static final MobParameter<AbstractFish> AbstractFish = MobParameter.of(AbstractFish.class, Description.ofEntityInterface(org.bukkit.entity.Fish.class));
	public static final MobParameter<ShoulderRidingEntity> ShoulderRidingEntity = MobParameter.of(ShoulderRidingEntity.class, Description.ofClass(org.bukkit.entity.Parrot.class));
	public static final MobParameter<AbstractSchoolingFish> AbstractSchoolingFish = MobParameter.of(AbstractSchoolingFish.class, Description.ofEntityInterface(SchoolableFish.class));
	public static final MobParameter<EnderMan> EnderMan = MobParameter.of(EnderMan.class, Description.ofClass(org.bukkit.entity.Enderman.class));
	public static final MobParameter<Drowned> Drowned = MobParameter.of(Drowned.class, Description.ofClass(org.bukkit.entity.Drowned.class));
	public static final MobParameter<Blaze> Blaze = MobParameter.of(Blaze.class, Description.ofClass(org.bukkit.entity.Blaze.class));
	public static final MobParameter<Bee> Bee = MobParameter.of(Bee.class, Description.ofClass(org.bukkit.entity.Bee.class));
	public static final MobParameter<Evoker> Evoker = MobParameter.of(Evoker.class, Description.ofClass(org.bukkit.entity.Evoker.class));
	public static final MobParameter<Phantom> Phantom = MobParameter.of(Phantom.class, Description.ofClass(org.bukkit.entity.Phantom.class));
	public static final MobParameter<PolarBear> PolarBear = MobParameter.of(PolarBear.class, Description.ofClass(org.bukkit.entity.PolarBear.class));
	public static final MobParameter<SpellcasterIllager> SpellcasterIllager = MobParameter.of(SpellcasterIllager.class, Description.ofClass(org.bukkit.entity.Spellcaster.class));
	public static final MobParameter<Vex> Vex = MobParameter.of(Vex.class, Description.ofClass(org.bukkit.entity.Vex.class));
	public static final MobParameter<WitherBoss> WitherBoss = MobParameter.of(WitherBoss.class, Description.ofClass(org.bukkit.entity.Wither.class));
	public static final MobParameter<Illusioner> Illusioner = MobParameter.of(Illusioner.class, Description.ofClass(org.bukkit.entity.Illusioner.class));
	public static final MobParameter<Mob> NeutralMob = MobParameter.of(Mob.class, Description.ofEntityInterface("Neutral ", org.bukkit.entity.Mob.class));
	public static final MobParameter<RangedAttackMob> RangedAttackMob = MobParameter.of(RangedAttackMob.class, Description.ofEntityInterface(org.bukkit.entity.Parrot.class));
	public static final MobParameter<Monster> Monster = MobParameter.of(Monster.class, Description.ofClass(org.bukkit.entity.Monster.class));
	public static final MobParameter<Monster> RangedAttackMonster = MobParameter.of(Monster.class, Description.ofEntityInterface("Ranged attack ", org.bukkit.entity.Monster.class), RangedAttackMob.class);
	public static final MobParameter<Monster> RangedCrossbowAttackMob = MobParameter.of(Monster.class, Description.ofEntityInterface("Ranged crossbow attack ", org.bukkit.entity.Monster.class), RangedAttackMob.class, CrossbowAttackMob.class);

}
